name: Build EPG

on:
  schedule:
    - cron: '15 */8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "RUN_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: checkout repo content
        uses: actions/checkout@v4
        
      - name: pull changes
        run: |
          git pull

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache TVGuide parts
        id: cache
        uses: actions/cache@v4
        with:
          path: cache
          key: cache-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            cache-${{ runner.os }}

      - name: execute py script
        run: python tvguide2xmltv.py  --api --platform sky --region london --now --now-days=1 -v --cache-ttl 86400 --output epg.xml

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add epg.xml
          git diff-index --quiet HEAD || (git commit -a -m "Updated EPG listings on $RUN_DATE" --allow-empty)


      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
